# -*- coding: utf-8 -*-
"""PavanGandhi_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15gwAiIf8Cvy0uwOxq5bVRMjPZlJMl4CQ
"""

import pandas as pd
from google.colab import files

# read the CSV file into a pandas dataframe
df = pd.read_csv("Text.csv")

# change the column names as desired
df.columns = ["timestamp", "status", "message"]

# convert the dataframe to a JSON file
df.to_json("file.json", orient="records")
print("JSON File created.")

#For Downloading the JSON file
#files.download('file.json') 

data = pd.read_json('file.json')
print(data)